### ISSUE TITLE
NullReferenceException when trying to Rasterize a Page to a PNG stream

### ISSUE THREAD

**Issue by Meteoroetem** [arklumpus/VectSharp#49]
I tried to run `VectSharp.Raster.Raster.SaveAsPNG(Page page, Stream stream, double scale =1)` and a NullReferenceException was thrown at runtime.
The exception:
```
Exception has occurred: CLR/System.NullReferenceException
An unhandled exception of type 'System.NullReferenceException' occurred in VectSharp.dll: 'Object reference not set to an instance of an object.'
   at VectSharp.GraphicsPath.AddText(Point origin, String text, Font font, TextBaselines textBaseline)
   at VectSharp.PDF.PDFContext.PathText(String text, Double x, Double y)
   at VectSharp.PDF.PDFContext.StrokeText(String text, Double x, Double y)
   at VectSharp.Graphics.CopyToIGraphicsContext(IGraphicsContext destinationContext)
   at VectSharp.PDF.PDFContextInterpreter.SaveAsPDF(Document document, Stream stream, TextOptions textOption, Boolean compressStreams, Dictionary`2 linkDestinations, FilterOption filterOption)
   at VectSharp.Raster.Raster.SaveAsPNG(Page page, Stream stream, Double scale)
   ...
```
I looked through the PDF manual and found the possible issue. In `VectSharp.PDF.PDFContext.PathText(String text, Double x, Double y)`'s definition
(copied from pdf manual at pg. 820 or pg. 876 of the complete PDF file):
```
private void PathText(string text, double x, double y)
00656 {
00657 GraphicsPath textPath = new GraphicsPath().AddText(x, y, text, Font, TextBaseline);
00658
00659 for (int j = 0; j < textPath.Segments.Count; j++)
00660 {
00661 switch (textPath.Segments[j].Type)
00662 {
00663 case VectSharp.SegmentType.Move:
00664 this.MoveTo(textPath.Segments[j].Point.X, textPath.Segments[j].Point.Y);
00665 break;
00666 case VectSharp.SegmentType.Line:
00667 this.LineTo(textPath.Segments[j].Point.X, textPath.Segments[j].Point.Y);
00668 break;
00669 case VectSharp.SegmentType.CubicBezier:
00670 this.CubicBezierTo(textPath.Segments[j].Points[0].X,
textPath.Segments[j].Points[0].Y, textPath.Segments[j].Points[1].X, textPath.Segments[j].Points[1].Y,
textPath.Segments[j].Points[2].X, textPath.Segments[j].Points[2].Y);
00671 break;
00672 case VectSharp.SegmentType.Close:
00673 this.Close();
00674 break;
00675 }
00676 }
00677 }
```
you're calling `VectSharp.GraphicsPath.AddText(Point origin, String text, Font font, TextBaselines textBaseline)` like `new GraphicsPath().AddText(x, y, text, Font, TextBaseline)`.
Maybe you can't do it like that? I'm not sure where's the un-initiated object to whom there's a reference. Maybe it's inside `VectSharp.GraphicsPath.AddText(Point origin, String text, Font font, TextBaselines textBaseline)`?
I'll appreciate any help and thanks in advance!

Here's the definition of `AddText`:
(pg. 1305 or pg. 1361 of the full PDF file):
```
public GraphicsPath AddText(Point origin, string text, Font font, TextBaselines textBaseline =
TextBaselines.Top)
00372 {
00373 Font.DetailedFontMetrics metrics = font.MeasureTextAdvanced(text);
00374
00375 Point baselineOrigin = origin;
00376
00377 switch (textBaseline)
00378 {
00379 case TextBaselines.Baseline:
00380 baselineOrigin = new Point(origin.X - metrics.LeftSideBearing, origin.Y);
00381 break;
00382 case TextBaselines.Top:
00383 baselineOrigin = new Point(origin.X - metrics.LeftSideBearing, origin.Y +
metrics.Top);
00384 break;
00385 case TextBaselines.Bottom:
00386 baselineOrigin = new Point(origin.X - metrics.LeftSideBearing, origin.Y +
metrics.Bottom);
00387 break;
00388 case TextBaselines.Middle:
00389 baselineOrigin = new Point(origin.X - metrics.LeftSideBearing, origin.Y +
(metrics.Top - metrics.Bottom) * 0.5 + metrics.Bottom);
00390 break;
00391 }
00392
00393 Point currentGlyphPlacementDelta = new Point();
00394 Point currentGlyphAdvanceDelta = new Point();
00395 Point nextGlyphPlacementDelta = new Point();
00396 Point nextGlyphAdvanceDelta = new Point();
00397
00398 for (int i = 0; i < text.Length; i++)
00399 {
00400 char c = text[i];
00401
00402 if (Font.EnableKerning && i < text.Length - 1)
00403 {
00404 currentGlyphPlacementDelta = nextGlyphPlacementDelta;
00405 currentGlyphAdvanceDelta = nextGlyphAdvanceDelta;
00406 nextGlyphAdvanceDelta = new Point();
00407 nextGlyphPlacementDelta = new Point();
00408
00409 TrueTypeFile.PairKerning kerning =
font.FontFamily.TrueTypeFile.Get1000EmKerning(c, text[i + 1]);
00410
00411 if (kerning != null)
00412 {
00413 currentGlyphPlacementDelta = new Point(currentGlyphPlacementDelta.X +
kerning.Glyph1Placement.X, currentGlyphPlacementDelta.Y + kerning.Glyph1Placement.Y);
00414 currentGlyphAdvanceDelta = new Point(currentGlyphAdvanceDelta.X +
kerning.Glyph1Advance.X, currentGlyphAdvanceDelta.Y + kerning.Glyph1Advance.Y);
00415
00416 nextGlyphPlacementDelta = new Point(nextGlyphPlacementDelta.X +
kerning.Glyph2Placement.X, nextGlyphPlacementDelta.Y + kerning.Glyph2Placement.Y);
00417 nextGlyphAdvanceDelta = new Point(nextGlyphAdvanceDelta.X +
kerning.Glyph2Advance.X, nextGlyphAdvanceDelta.Y + kerning.Glyph2Advance.Y);
00418 }
00419 }
00420
00421 TrueTypeFile.TrueTypePoint[][] glyphPaths =
font.FontFamily.TrueTypeFile.GetGlyphPath(c, font.FontSize);
00422
00423 for (int j = 0; j < glyphPaths.Length; j++)
00424 {
00425 for (int k = 0; k < glyphPaths[j].Length; k++)
00426 {
00427 if (k == 0)
00428 {
00429 this.MoveTo(glyphPaths[j][k].X + baselineOrigin.X +
currentGlyphPlacementDelta.X, -glyphPaths[j][k].Y + baselineOrigin.Y + currentGlyphPlacementDelta.Y);
00430 }
00431 else
00432 {
00433 if (glyphPaths[j][k].IsOnCurve)
00434 {
00435 this.LineTo(glyphPaths[j][k].X + baselineOrigin.X +
currentGlyphPlacementDelta.X, -glyphPaths[j][k].Y + baselineOrigin.Y + currentGlyphPlacementDelta.Y);
00436 }
00437 else
00438 {
00439 Point startPoint = this.Segments.Last().Point;
00440 Point quadCtrl = new Point(glyphPaths[j][k].X + baselineOrigin.X +
currentGlyphPlacementDelta.X, -glyphPaths[j][k].Y + baselineOrigin.Y + currentGlyphPlacementDelta.Y);
Generated by Doxygen
1306 File Documentation
00441 Point endPoint = new Point(glyphPaths[j][k + 1].X + baselineOrigin.X +
currentGlyphPlacementDelta.X, -glyphPaths[j][k + 1].Y + baselineOrigin.Y +
currentGlyphPlacementDelta.Y);
00442
00443
00444 Point ctrl1 = new Point(startPoint.X / 3 + 2 * quadCtrl.X / 3,
startPoint.Y / 3 + 2 * quadCtrl.Y / 3);
00445 Point ctrl2 = new Point(endPoint.X / 3 + 2 * quadCtrl.X / 3,
endPoint.Y / 3 + 2 * quadCtrl.Y / 3);
00446
00447 this.CubicBezierTo(ctrl1, ctrl2, endPoint);
00448
00449 k++;
00450 }
00451 }
00452 }
00453
00454 this.Close();
00455 }
00456
00457 baselineOrigin.X += (font.FontFamily.TrueTypeFile.Get1000EmGlyphWidth(c) +
currentGlyphAdvanceDelta.X) * font.FontSize / 1000;
00458 baselineOrigin.Y += (currentGlyphAdvanceDelta.Y) * font.FontSize / 1000;
00459 }
00460 return this;
00461 }
```

**Comment by arklumpus** [comment]
Hi, I would need to see some more of your code to be able to say for sure, but I think you are drawing text with a `FontFamily` that has not been initialised properly (check the `TrueTypeFile` property: if it is `null`, you have your culprit).

How are you creating the `Font` object?

**Comment by arklumpus** [comment]
Perfect! BTW, the problem may be that it's `Helvetica` and not `Halvetica` 😅 To avoid this issue, you can use the enum:

```CSharp
FontFamily.ResolveFontFamily(FontFamily.StandardFontFamilies.Helvetica);
```
