### ISSUE TITLE
SVG File Parsing Issue

### ISSUE THREAD

**Issue by broderickt2** [arklumpus/VectSharp#52]
I took the memory stream for a file and attempted to pass it into `Parser.FromStream` and this function threw the error: "Input string was not in a correct format.". I have tested other SVG files by the way such as the sample "SurgeonFish" from the documentation and these load just fine. I think there is an issue with the file itself. Maybe it is setup differently than the library expected. I hope there is an easy solution here that can be implemented to help improve the library.

Here is the stack trace:
```
   at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   at VectSharp.SVG.Parser.InterpretPathObject(XmlNode currObject, Graphics gpr, Double width, Double height, Double diagonal, PresentationAttributes attributes, IEnumerable`1 styleSheets, Dictionary`2 gradients)
   at VectSharp.SVG.Parser.InterpretSVGElement(XmlNode currObject, Graphics gpr, PresentationAttributes attributes, Double width, Double height, Double diagonal, IEnumerable`1 styleSheets, Dictionary`2 gradients, Dictionary`2 filters)
   at VectSharp.SVG.Parser.InterpretSVGChildren(XmlNode svgObject, Graphics gpr, PresentationAttributes attributes, Double width, Double height, Double diagonal, IEnumerable`1 styleSheets, Dictionary`2 gradients, Dictionary`2 filters)
   at VectSharp.SVG.Parser.InterpretSVGObject(XmlNode svgObject, Graphics gpr, PresentationAttributes attributes, IEnumerable`1 styleSheets, Dictionary`2 gradients, Dictionary`2 filters, Dictionary`2 masks)
   at VectSharp.SVG.Parser.FromString(String svgSource)
   at VectSharp.SVG.Parser.FromStream(Stream svgSourceStream)
```

Here is the file that caused the error:
![cat](https://github.com/arklumpus/VectSharp/assets/93213727/47ed909f-65aa-4774-a9d2-26f1b87515f5)

Thanks for any help in advance.

**Comment by arklumpus** [comment]
Hi, thank you for noticing this! The issue should now be solved in VectSharp.SVG 1.8.2-a7 (I just pushed it to NuGet, it may take a few minutes to appear).

The reason was that in the SVG file, there were some path data points specified as something like `-13.457.902`, which should be interpreted as `-13.457 0.902`... I have modified the tokenizer to treat the `.` as a token separator if a decimal point is already present in the current code.

Please let me know if you have any other issues!

**Comment by broderickt2** [comment]
Hi,

I just pulled the prerelease from NuGet and tested the changes. It works on my end; thanks for the quick fix here!
